- name: Check if /home/{{ current_user.stdout }}/dotfiles directory exist
  stat:
    path: "/home/{{ current_user.stdout }}/dotfiles"
  register: dotfiles_stats

- name: Clone dotfiles repo
  git:
    repo: https://github.com/Zaruun/dotfiles
    dest: "/home/{{ current_user.stdout }}/dotfiles"
  when: dotfiles_stats.stat.exists == False